# Generated by Django 5.2.10 on 2026-02-08 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('arr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_schools', models.IntegerField(default=0)),
                ('active_schools', models.IntegerField(default=0)),
                ('new_schools_this_month', models.IntegerField(default=0)),
                ('churn_count', models.IntegerField(default=0)),
                ('churn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cac', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ltv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('region_distribution', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'public_investor_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarketingSpend',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('channel', models.CharField(help_text='e.g., Google Ads, LinkedIn, Sales Team', max_length=50)),
            ],
            options={
                'db_table': 'public_marketing_spend',
                'ordering': ['-month'],
                'unique_together': {('month', 'channel')},
            },
        ),
    ]
