# Generated by Django 5.2.10 on 2026-02-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='investormetric',
            table='analytics_investor_metrics',
        ),
        migrations.AlterModelTable(
            name='marketingspend',
            table='analytics_marketing_spend',
        ),
    ]
