# Generated by Django 6.0 on 2025-12-24 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0002_alter_staffattendance_unique_together_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Period 1, Morning Break', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_type', models.CharField(choices=[('PERIOD', 'Period'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('ASSEMBLY', 'Assembly'), ('ACTIVITY', 'Activity')], default='PERIOD', max_length=20)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order')),
                ('duration', models.PositiveIntegerField(editable=False, help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Attendance Period',
                'verbose_name_plural': 'Attendance Periods',
                'ordering': ['order', 'start_time'],
                'unique_together': {('name', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['-month', 'student'],
                'indexes': [models.Index(fields=['student', 'month'], name='attendance__student_9fd22a_idx'), models.Index(fields=['academic_year', 'month'], name='attendance__academi_468c90_idx')],
                'unique_together': {('student', 'academic_year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'National Holiday'), ('REGIONAL', 'Regional Holiday'), ('SCHOOL', 'School Holiday'), ('FESTIVAL', 'Festival'), ('WEEKEND', 'Weekend'), ('EXAM', 'Examination'), ('VACATION', 'Vacation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Optional holiday (staff can choose to work)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'academic_year'], name='attendance__date_b390a5_idx')],
                'unique_together': {('date', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('WEEKEND', 'Weekend'), ('WORK_FROM_HOME', 'Work From Home')], default='PRESENT', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated working hours', max_digits=4, null=True)),
                ('biometric_verified', models.BooleanField(default=False)),
                ('biometric_device_id', models.CharField(blank=True, max_length=50)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours', max_digits=4)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance Records',
                'ordering': ['-date', 'staff_member'],
                'indexes': [models.Index(fields=['staff_member', 'date'], name='attendance__staff_m_e9dcda_idx'), models.Index(fields=['date', 'status'], name='attendance__date_3dbb50_idx')],
                'unique_together': {('staff_member', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('EARNED', 'Earned Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('COMPENSATORY', 'Compensatory Off'), ('UNPAID', 'Unpaid Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leaves/staff/%Y/%m/')),
                ('total_days', models.PositiveIntegerField(default=1, editable=False)),
                ('is_half_day', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_leaves', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Leave',
                'verbose_name_plural': 'Staff Leaves',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['staff_member', 'status'], name='attendance__staff_m_dacbc7_idx'), models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_343288_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('biometric_verified', models.BooleanField(default=False)),
                ('biometric_device_id', models.CharField(blank=True, max_length=50)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='academics.academicyear')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendance', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance', to='attendance.attendanceperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance Records',
                'ordering': ['-date', 'student'],
                'indexes': [models.Index(fields=['student', 'date'], name='attendance__student_0335ea_idx'), models.Index(fields=['date', 'status'], name='attendance__date_514473_idx'), models.Index(fields=['academic_year', 'date'], name='attendance__academi_51d374_idx')],
                'unique_together': {('student', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('EMERGENCY', 'Emergency Leave'), ('FAMILY', 'Family Event'), ('MEDICAL', 'Medical Appointment'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Medical certificate, etc.', null=True, upload_to='leaves/student/%Y/%m/')),
                ('total_days', models.PositiveIntegerField(default=1, editable=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_leaves', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Parent/Guardian who requested', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Leave',
                'verbose_name_plural': 'Student Leaves',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='attendance__student_b9d099_idx'), models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_c186e5_idx')],
            },
        ),
    ]
