# Generated by Django 5.2.10 on 2026-02-05 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendanceperiod_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
