# Generated by Django 5.2.10 on 2026-02-08 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_lessonplan_syllabusunit_lessonplanitem'),
        ('attendance', '0003_attendancesummary_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendanceLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('sync_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the sync batch from client')),
                ('client_timestamp', models.DateTimeField(help_text='Timestamp when attendance was marked on client')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for conflict resolution')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendance_logs', to='attendance.attendanceperiod')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='academics.section')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Attendance Log',
                'verbose_name_plural': 'Class Attendance Logs',
                'ordering': ['-date', '-client_timestamp'],
                'indexes': [models.Index(fields=['section', 'date'], name='attendance__section_768101_idx'), models.Index(fields=['date', 'taken_by'], name='attendance__date_5baf3e_idx')],
                'unique_together': {('section', 'date', 'period')},
            },
        ),
    ]
