# Generated by Django 5.2.10 on 2026-02-08 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_user_language_preference'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('LEAVE', 'Leave Application'), ('FEE_CONCESSION', 'Fee Concession'), ('TRANSFER_CERT', 'Transfer Certificate'), ('GENERIC', 'Generic Request')], default='GENERIC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('content_types', models.ManyToManyField(blank=True, help_text='Models this workflow applies to', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Workflow Configuration',
                'verbose_name_plural': 'Workflow Configurations',
                'db_table': 'workflow_configurations',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="e.g. 'HM Approval'", max_length=100)),
                ('step_order', models.PositiveIntegerField(help_text='Sequence number (1, 2, 3...)')),
                ('is_final_step', models.BooleanField(default=False, help_text='If approved, workflow is completed')),
                ('can_reject', models.BooleanField(default=True, help_text='Can the approver reject?')),
                ('on_rejection', models.CharField(choices=[('TERMINATE', 'Terminate Workflow'), ('BACK_TO_START', 'Restart Workflow'), ('BACK_TO_PREVIOUS', 'Go Back One Step')], default='TERMINATE', max_length=20)),
                ('approver_role', models.ForeignKey(blank=True, help_text='Role required to approve this step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='authentication.role')),
                ('approver_user', models.ForeignKey(blank=True, help_text='Specific user required to approve (overrides role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('workflow_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowconfiguration')),
            ],
            options={
                'db_table': 'workflow_steps',
                'ordering': ['step_order'],
                'unique_together': {('workflow_config', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflows.workflowconfiguration')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_requests', to='workflows.workflowstep')),
            ],
            options={
                'db_table': 'workflow_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('INITIATE', 'Initiated'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('REQUEST_CHANGE', 'Request Change'), ('CANCEL', 'Cancelled')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflows.workflowrequest')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowstep')),
            ],
            options={
                'db_table': 'workflow_action_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_re_content_51c464_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['status'], name='workflow_re_status_81aef6_idx'),
        ),
    ]
