# Generated by Django 4.2.7 on 2026-02-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_event_options_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
    ]
