# Generated by Django 4.2.7 on 2026-02-01 05:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_convert_to_encrypted_fields'),
        ('staff', '0004_remove_staffdocument_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('hostel_type', models.CharField(choices=[('BOYS', 'Boys Hostel'), ('GIRLS', 'Girls Hostel'), ('CO_ED', 'Co-Education')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('warden', models.ForeignKey(blank=True, help_text='Warden in charge of this hostel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wardened_hostels', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostel_hostels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('DORMITORY', 'Dormitory')], default='DOUBLE', max_length=15)),
                ('capacity', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('PARTIALLY_OCCUPIED', 'Partially Occupied'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'hostel_rooms',
                'ordering': ['hostel', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACKS', 'Snacks'), ('DINNER', 'Dinner')], max_length=10)),
                ('items', models.TextField(help_text='Comma-separated list of menu items')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('hostel', models.ForeignKey(blank=True, help_text='If null, applies to all hostels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mess_menus', to='hostel.hostel')),
            ],
            options={
                'verbose_name': 'Mess Menu',
                'verbose_name_plural': 'Mess Menus',
                'db_table': 'hostel_mess_menus',
                'ordering': ['day', 'meal'],
            },
        ),
        migrations.CreateModel(
            name='HostelVisitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('purpose', models.CharField(blank=True, max_length=300)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='hostel.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_visitors', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Visitor',
                'verbose_name_plural': 'Hostel Visitors',
                'db_table': 'hostel_visitors',
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='HostelComplaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('FURNITURE', 'Furniture'), ('CLEANLINESS', 'Cleanliness'), ('FOOD', 'Food Quality'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.hostel')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_hostel_complaints', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='hostel.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_complaints', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Complaint',
                'verbose_name_plural': 'Hostel Complaints',
                'db_table': 'hostel_complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave')], default='PRESENT', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hostel.hostel')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_attendance', to='students.student')),
            ],
            options={
                'verbose_name': 'Hostel Attendance',
                'verbose_name_plural': 'Hostel Attendance Records',
                'db_table': 'hostel_attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_date', models.DateField()),
                ('vacated_date', models.DateField(blank=True, null=True)),
                ('bed_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student')),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
                'db_table': 'hostel_room_allocations',
                'ordering': ['-allocated_date'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='hostel_room_student_8c51b2_idx'), models.Index(fields=['room', 'is_active'], name='hostel_room_room_id_956dce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='hostel_room_status_00d8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hostel', 'floor'], name='hostel_room_hostel__cdddd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together={('hostel', 'day', 'meal')},
        ),
        migrations.AddIndex(
            model_name='hostelcomplaint',
            index=models.Index(fields=['status'], name='hostel_comp_status_b9b2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelcomplaint',
            index=models.Index(fields=['category'], name='hostel_comp_categor_086b46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelattendance',
            unique_together={('student', 'date')},
        ),
    ]
