# Generated by Django 6.0 on 2025-12-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='staffattendance',
            name='staff_atten_date_5ba088_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffleave',
            name='staff_leave_status_3687a5_idx',
        ),
        migrations.RemoveField(
            model_name='staffleave',
            name='approved_rejected_by',
        ),
        migrations.RemoveField(
            model_name='staffleave',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='staffleave',
            name='staff_member',
        ),
        migrations.DeleteModel(
            name='StaffAttendance',
        ),
        migrations.DeleteModel(
            name='StaffLeave',
        ),
    ]
