# Generated by Django 6.0 on 2026-01-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='designation',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('HEAD_TEACHER', 'Head Teacher'), ('SENIOR_TEACHER', 'Senior Teacher'), ('TEACHER', 'Teacher'), ('JUNIOR_TEACHER', 'Junior Teacher'), ('PRIMARY_TEACHER', 'Primary Teacher'), ('PRT', 'Primary Teacher (PRT)'), ('TGT', 'Trained Graduate Teacher (TGT)'), ('PGT', 'Post Graduate Teacher (PGT)'), ('LIBRARIAN', 'Librarian'), ('LAB_ASSISTANT', 'Lab Assistant'), ('SPORTS_COACH', 'Sports Coach'), ('SPORTS_TEACHER', 'Sports Teacher'), ('COUNSELOR', 'Counselor'), ('ACCOUNTANT', 'Accountant'), ('CLERK', 'Clerk'), ('OFFICE_ASSISTANT', 'Office Assistant'), ('PEON', 'Peon'), ('SECURITY_GUARD', 'Security Guard'), ('DRIVER', 'Driver'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
