# Generated by Django 6.0 on 2026-01-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffmember_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdocument',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='staffexperience',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='staffqualification',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffexperience',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffqualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffqualification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
