# Generated by Django 5.2.10 on 2026-02-09 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_lessonplan_syllabusunit_lessonplanitem'),
        ('authentication', '0005_user_language_preference'),
        ('staff', '0004_remove_staffdocument_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., {"house_id": "...", "activity_id": "..."})')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role_assignments', to='academics.academicyear')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='authentication.role')),
                ('section', models.ForeignKey(blank=True, help_text='Assigned section (for Class Teachers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role_assignments', to='academics.section')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Role Assignment',
                'verbose_name_plural': 'Staff Role Assignments',
                'db_table': 'staff_role_assignments',
                'unique_together': {('staff_member', 'role', 'academic_year', 'section')},
            },
        ),
    ]
