# Generated by Django 4.2.7 on 2026-02-16 07:37

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffroleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[apps.core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='current_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='current_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='current_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='current_pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[apps.core.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='current_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[apps.core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='permanent_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='permanent_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[apps.core.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[apps.core.validators.validate_phone_number]),
        ),
    ]
