# Generated by Django 6.0 on 2026-02-02 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_auditlog_core_auditl_action_096de0_idx_and_more'),
        ('tenants', '0004_alter_school_db_password_alter_school_schema_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Tenant (school) this audit log entry belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.school'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['school', 'timestamp'], name='audit_logs_school__3bfbd5_idx'),
        ),
    ]
