# Generated by Django 4.2.7 on 2026-02-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='integration_credential_id',
            field=models.UUIDField(blank=True, help_text='ID of the integration credential that performed this action', null=True),
        ),
    ]
