# Generated by Django 5.2.10 on 2026-02-08 11:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_convert_to_encrypted_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('FEE_DUE', 'Fee Demand (Debit)'), ('PAYMENT', 'Payment Received (Credit)'), ('DISCOUNT', 'Discount/Concession (Credit)'), ('REFUND', 'Refund Issued (Debit)'), ('REVERSAL', 'Correction/Reversal')], max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Final amount after taxes and TDS', max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('reference_id', models.CharField(help_text='ID of the source document (Invoice ID, Payment ID, etc.)', max_length=100)),
                ('description', models.TextField()),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('entry_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_ledger_entries', to='students.student')),
            ],
            options={
                'db_table': 'finance_student_ledger',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='finance_stu_student_505d1a_idx'), models.Index(fields=['entry_hash'], name='finance_stu_entry_h_49852d_idx')],
            },
        ),
    ]
