# Generated by Django 4.2.7 on 2026-02-15 12:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0008_alter_tenantconfig_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('PLATFORM_REVENUE', 'Platform Revenue'), ('SCHOOL_COLLECTION', 'School Collection'), ('PARTNER_COMMISSION', 'Partner Commission'), ('INVESTOR_PAYOUT', 'Investor Payout'), ('CASH_SETTLEMENT', 'Cash/Bank Settlement')], max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, help_text='Null for global platform accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'verbose_name_plural': 'Ledger Accounts',
                'db_table': 'finance_ledger_accounts',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.UUIDField(blank=True, help_text='Link to external record (e.g. Payment ID, Subscription ID)', null=True)),
                ('description', models.TextField()),
                ('transaction_type', models.CharField(choices=[('SUBSCRIPTION', 'Platform Subscription'), ('SCHOOL_FEE', 'School Fee Collection'), ('COMMISSION', 'Partner Commission Accrual'), ('PAYOUT', 'Partner/Investor Payout'), ('SETTLEMENT', 'Inter-account Settlement'), ('ADJUSTMENT', 'Audit Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('VOID', 'Voided')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('transaction_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'finance_ledger_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance_ledger.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance_ledger.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'finance_ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report_name', models.CharField(max_length=255)),
                ('data', models.JSONField(help_text='Balances of all accounts at snapshot time')),
                ('integrity_hash', models.CharField(editable=False, max_length=64)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_ledger_snapshots',
            },
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_ledger_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
