# Generated by Django 6.0 on 2025-12-24 08:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0002_alter_staffattendance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('LIBRARY', 'Library'), ('AUDITORIUM', 'Auditorium'), ('SPORTS', 'Sports Facility'), ('COMPUTER_LAB', 'Computer Lab'), ('SCIENCE_LAB', 'Science Lab'), ('OTHER', 'Other')], max_length=20)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(help_text='Maximum seating capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('facilities', models.JSONField(blank=True, default=list, help_text='List of available facilities (projector, AC, etc.)')),
                ('is_available', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
                'db_table': 'timetable_room_allocation',
                'ordering': ['building', 'floor', 'room_number'],
                'indexes': [models.Index(fields=['room_type'], name='timetable_r_room_ty_84489c_idx'), models.Index(fields=['is_available'], name='timetable_r_is_avai_203d1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Period 1, Morning Break', max_length=100)),
                ('slot_type', models.CharField(choices=[('PERIOD', 'Period'), ('BREAK', 'Break'), ('LUNCH', 'Lunch Break'), ('ASSEMBLY', 'Assembly'), ('ACTIVITY', 'Activity')], default='PERIOD', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes (auto-calculated)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('order', models.IntegerField(default=0, help_text='Display order in timetable')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'timetable_time_slots',
                'ordering': ['order', 'start_time'],
                'indexes': [models.Index(fields=['order'], name='timetable_t_order_17b856_idx'), models.Index(fields=['start_time'], name='timetable_t_start_t_cc5745_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('room_number', models.CharField(blank=True, help_text='Classroom/Lab number', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='academics.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.section')),
                ('subject', models.ForeignKey(blank=True, help_text='Subject for this period (null for breaks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher assigned to this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='staff.staffmember')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='timetable.timeslot')),
            ],
            options={
                'verbose_name': 'Class Timetable',
                'verbose_name_plural': 'Class Timetables',
                'db_table': 'timetable_class_timetable',
                'ordering': ['day_of_week', 'time_slot__order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of substitution')),
                ('reason', models.TextField(help_text='Reason for substitution')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='academics.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_substitutions', to=settings.AUTH_USER_MODEL)),
                ('original_entry', models.ForeignKey(help_text='Original timetable entry', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.classtimetable')),
                ('original_teacher', models.ForeignKey(help_text='Teacher who is absent', on_delete=django.db.models.deletion.CASCADE, related_name='original_classes', to='staff.staffmember')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_substitutions', to=settings.AUTH_USER_MODEL)),
                ('substitute_teacher', models.ForeignKey(help_text='Teacher who will substitute', on_delete=django.db.models.deletion.CASCADE, related_name='substitute_classes', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Timetable Substitution',
                'verbose_name_plural': 'Timetable Substitutions',
                'db_table': 'timetable_substitutions',
                'ordering': ['-date', 'original_entry__time_slot__order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_data', models.JSONField(help_text='JSON structure containing the timetable template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Template',
                'verbose_name_plural': 'Timetable Templates',
                'db_table': 'timetable_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='academics.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='academics.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_timetable', to='staff.staffmember')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='timetable.timeslot')),
            ],
            options={
                'verbose_name': 'Teacher Timetable',
                'verbose_name_plural': 'Teacher Timetables',
                'db_table': 'timetable_teacher_timetable',
                'ordering': ['day_of_week', 'time_slot__order'],
                'indexes': [models.Index(fields=['academic_year', 'teacher'], name='timetable_t_academi_9e99e8_idx'), models.Index(fields=['day_of_week'], name='timetable_t_day_of__d07a93_idx')],
                'unique_together': {('academic_year', 'teacher', 'day_of_week', 'time_slot')},
            },
        ),
        migrations.AddIndex(
            model_name='classtimetable',
            index=models.Index(fields=['academic_year', 'class_obj', 'section'], name='timetable_c_academi_ccaaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimetable',
            index=models.Index(fields=['day_of_week'], name='timetable_c_day_of__30b524_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimetable',
            index=models.Index(fields=['teacher'], name='timetable_c_teacher_1fa048_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classtimetable',
            unique_together={('academic_year', 'class_obj', 'section', 'day_of_week', 'time_slot')},
        ),
        migrations.AddIndex(
            model_name='timetablesubstitution',
            index=models.Index(fields=['date', 'status'], name='timetable_s_date_d39a81_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablesubstitution',
            index=models.Index(fields=['original_teacher'], name='timetable_s_origina_75ff0a_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablesubstitution',
            index=models.Index(fields=['substitute_teacher'], name='timetable_s_substit_9457d3_idx'),
        ),
    ]
