# Generated by Django 4.2.7 on 2026-02-01 05:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staffdocument_deleted_by_and_more'),
        ('academics', '0002_remove_academicyear_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableGenerationConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Configuration name', max_length=200)),
                ('working_days', models.JSONField(default=list, help_text='Working days for generation, e.g. ["MONDAY","TUESDAY",...]')),
                ('algorithm', models.CharField(choices=[('CSP_BACKTRACK', 'Constraint Satisfaction + Backtracking'), ('GENETIC', 'Genetic Algorithm'), ('HYBRID', 'Hybrid CSP + Optimization')], default='HYBRID', max_length=20)),
                ('max_iterations', models.IntegerField(default=1000, help_text='Maximum iterations for optimization', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('population_size', models.IntegerField(default=50, help_text='Population size for genetic algorithm', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)])),
                ('weight_workload_balance', models.FloatField(default=0.8, help_text='Weight for teacher workload balance across days', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('weight_subject_spread', models.FloatField(default=0.7, help_text='Weight for spreading subject periods across the week', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('weight_teacher_preference', models.FloatField(default=0.6, help_text='Weight for teacher time preference satisfaction', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('weight_room_optimization', models.FloatField(default=0.5, help_text='Weight for minimizing room changes', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('weight_no_consecutive_heavy', models.FloatField(default=0.7, help_text='Weight for avoiding consecutive heavy subjects', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('custom_rules', models.JSONField(blank=True, default=list, help_text='Custom scheduling rules in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_configs', to='academics.academicyear')),
                ('classes', models.ManyToManyField(help_text='Classes to generate timetable for', related_name='generation_configs', to='academics.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_configs', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ManyToManyField(blank=True, help_text='Specific sections (if empty, all sections for selected classes)', related_name='generation_configs', to='academics.section')),
            ],
            options={
                'verbose_name': 'Timetable Generation Config',
                'verbose_name_plural': 'Timetable Generation Configs',
                'db_table': 'timetable_generation_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the teacher is available on this day')),
                ('available_from', models.TimeField(blank=True, help_text='Partial-day availability start time', null=True)),
                ('available_until', models.TimeField(blank=True, help_text='Partial-day availability end time', null=True)),
                ('max_periods_per_day', models.IntegerField(default=6, help_text='Maximum teaching periods this teacher can have on this day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_consecutive_periods', models.IntegerField(default=3, help_text='Maximum consecutive periods without a break', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('preferred_time_slots', models.JSONField(blank=True, default=list, help_text='Preferred period IDs for this day')),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='academics.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Teacher Availability',
                'verbose_name_plural': 'Teacher Availabilities',
                'db_table': 'timetable_teacher_availability',
                'ordering': ['teacher', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPeriodRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periods_per_week', models.IntegerField(help_text='Number of periods per week for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('requires_lab', models.BooleanField(default=False, help_text='Whether this subject requires a lab room')),
                ('preferred_room_type', models.CharField(blank=True, choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('LIBRARY', 'Library'), ('AUDITORIUM', 'Auditorium'), ('SPORTS', 'Sports Facility'), ('COMPUTER_LAB', 'Computer Lab'), ('SCIENCE_LAB', 'Science Lab'), ('OTHER', 'Other')], help_text='Preferred room type for this subject', max_length=20, null=True)),
                ('consecutive_periods', models.IntegerField(default=1, help_text='Number of consecutive periods (e.g., 2 for double-period labs)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('preferred_time_slots', models.JSONField(blank=True, default=list, help_text='Preferred time of day: ["MORNING", "AFTERNOON"]')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_period_requirements', to='academics.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_requirements', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_requirements', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Preferred teacher for this subject-class combination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_requirements', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Subject Period Requirement',
                'verbose_name_plural': 'Subject Period Requirements',
                'db_table': 'timetable_subject_period_requirements',
                'ordering': ['class_obj__name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableGenerationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating Input'), ('GENERATING', 'Generating'), ('OPTIMIZING', 'Optimizing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('APPLIED', 'Applied to Timetable'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20)),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_message', models.CharField(blank=True, max_length=500)),
                ('generated_timetable', models.JSONField(blank=True, default=dict, help_text='Full generated timetable data in JSON')),
                ('fitness_score', models.FloatField(blank=True, help_text='Optimization fitness score (0-100)', null=True)),
                ('conflicts_found', models.IntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list, help_text='List of warning messages from generation')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('rollback_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of previous timetable before applying generation results')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='timetable.timetablegenerationconfig')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Generation Run',
                'verbose_name_plural': 'Timetable Generation Runs',
                'db_table': 'timetable_generation_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='timetable_g_status_4ff8b9_idx'), models.Index(fields=['config'], name='timetable_g_config__02dbfe_idx'), models.Index(fields=['-created_at'], name='timetable_g_created_290ff8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='timetablegenerationconfig',
            index=models.Index(fields=['academic_year'], name='timetable_g_academi_ff1851_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablegenerationconfig',
            index=models.Index(fields=['is_active'], name='timetable_g_is_acti_dc8dea_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['academic_year', 'teacher'], name='timetable_t_academi_5dd932_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('academic_year', 'teacher', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='subjectperiodrequirement',
            index=models.Index(fields=['academic_year', 'class_obj'], name='timetable_s_academi_92863d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectperiodrequirement',
            unique_together={('academic_year', 'class_obj', 'subject')},
        ),
    ]
