# Generated by Django 5.2.10 on 2026-02-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetablegenerationconfig_teacheravailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teachertimetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetablesubstitution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetabletemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
