# Generated by Django 6.0 on 2025-12-25 05:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('exam_type', models.CharField(choices=[('FORMATIVE', 'Formative Assessment'), ('SUMMATIVE', 'Summative Assessment'), ('DIAGNOSTIC', 'Diagnostic Test'), ('BENCHMARK', 'Benchmark Test')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage weightage in final grade', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Types',
                'db_table': 'examinations_exam_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'db_table': 'examinations_grade_scale',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('result_date', models.DateField(blank=True, help_text='Date when results will be published', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='General instructions for students')),
                ('is_published', models.BooleanField(default=False, help_text='Whether results are published to students')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='academics.academicyear')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='examinations.examtype')),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='examinations.gradescale')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'db_table': 'examinations_examinations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_max_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative Grade Point Average', max_digits=4, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=10)),
                ('rank', models.IntegerField(blank=True, help_text='Rank in class', null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('subjects_passed', models.IntegerField(default=0)),
                ('subjects_failed', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.class')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.examination')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'db_table': 'examinations_exam_results',
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(help_text='Exam duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_passing_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.class')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.examination')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'db_table': 'examinations_exam_schedule',
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(help_text='e.g., A+, A, B+', max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_point', models.DecimalField(decimal_places=2, help_text='GPA value for this grade', max_digits=4)),
                ('description', models.CharField(blank=True, help_text='e.g., Excellent, Good, Average', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='examinations.gradescale')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'examinations_grades',
                'ordering': ['grade_scale', 'order', '-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(help_text='Complete report card data in JSON format')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('exam_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='examinations.examresult')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'db_table': 'examinations_report_cards',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXEMPTED', 'Exempted')], default='PRESENT', max_length=20)),
                ('is_passed', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='examinations.examschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'db_table': 'examinations_student_marks',
                'ordering': ['exam_schedule', 'student'],
            },
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['examination', 'class_obj', 'section'], name='examination_examina_075b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['percentage'], name='examination_percent_1f0237_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['rank'], name='examination_rank_acf6a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('examination', 'student')},
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['examination', 'class_obj', 'section'], name='examination_examina_e7a057_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['exam_date'], name='examination_exam_da_9c15fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('examination', 'class_obj', 'section', 'subject')},
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['grade_scale', 'min_percentage', 'max_percentage'], name='examination_grade_s_dbe8eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('grade_scale', 'grade')},
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['academic_year', 'status'], name='examination_academi_1fedaa_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['start_date', 'end_date'], name='examination_start_d_fb3b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['student', 'exam_schedule'], name='examination_student_c60ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['is_passed'], name='examination_is_pass_964969_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('exam_schedule', 'student')},
        ),
    ]
