# Generated by Django 6.0 on 2026-01-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        # ID alterations removed to preserve UUID primary keys

    ]
