# Generated by Django 5.2.10 on 2026-02-03 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_examhall_examscheduleconfig_reportcard_academic_year_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='examination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),

        migrations.AlterField(
            model_name='studentmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
