# Generated by Django 4.2.7 on 2026-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Bank/Gateway transaction ID', max_length=100, null=True, unique=True),
        ),
    ]
