# Generated by Django 5.2.10 on 2026-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='auth_login_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='auth_login_ip_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='auth_login_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='auth_reset_token_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='auth_reset_used_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='auth_reset_expires_idx',
        ),
        migrations.RemoveIndex(
            model_name='permission',
            name='auth_perm_module_idx',
        ),
        migrations.RemoveIndex(
            model_name='permission',
            name='auth_perm_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='permission',
            name='auth_perm_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='auth_role_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='auth_role_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_user_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_user_email_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='auth_user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='auth_user_role_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='auth_user_role_expires_idx',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
