# Generated by Django 4.2.7 on 2026-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_loginhistory_auth_login_user_time_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi')], default='en', help_text='Preferred language for interface and notifications', max_length=10),
        ),
    ]
