# Generated by Django 5.2.10 on 2026-02-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('SCHOOL_ADMIN', 'School Administrator'), ('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('PARTNER', 'Partner'), ('INVESTOR', 'Investor')], db_index=True, max_length=20),
        ),
    ]
