# Generated by Django 4.2.7 on 2026-02-16 07:47

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Indian phone number (10 digits)', max_length=15, null=True, unique=True, validators=[apps.core.validators.validate_phone_number]),
        ),
    ]
