# Generated by Django 5.2.10 on 2026-02-07 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('UDISE_PLUS', 'UDISE+ Report'), ('RTE_ADMISSIONS', 'RTE Admissions Report'), ('RTE_FEES', 'RTE Fee Concessions')], max_length=50)),
                ('academic_year', models.CharField(help_text='YYYY-YYYY', max_length=9)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='government_reports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_gov_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'government_report_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTEComplianceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('total_intake_capacity', models.IntegerField(help_text='Total Entry Level Seats')),
                ('reserved_seats_rte', models.IntegerField(help_text='25% Reserved Seats')),
                ('seats_filled_rte', models.IntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_rte_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rte_compliance_records',
                'ordering': ['-academic_year'],
            },
        ),
    ]
