# Generated by Django 5.2.10 on 2026-02-08 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgeneration',
            name='generated_format',
            field=models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF')], default='EXCEL', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='report_type',
            field=models.CharField(choices=[('UDISE_PLUS', 'UDISE+ Report'), ('RTE_ADMISSIONS', 'RTE Admissions Report'), ('RTE_FEES', 'RTE Fee Concessions'), ('BOARD_EXPORT', 'Board Exam Export')], max_length=50),
        ),
        migrations.CreateModel(
            name='UDISECodeMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('GENDER', 'Gender'), ('SOCIAL_CATEGORY', 'Social Category'), ('RELIGION', 'Religion'), ('DISABILITY', 'Disability Type'), ('MEDIUM_OF_INSTRUCTION', 'Medium of Instruction')], max_length=50)),
                ('internal_value', models.CharField(help_text="Value in our system (e.g., 'M', 'SC')", max_length=100)),
                ('udise_code', models.CharField(help_text='Corresponding UDISE+ Code', max_length=50)),
                ('udise_description', models.CharField(blank=True, help_text='Description as per UDISE manual', max_length=255)),
            ],
            options={
                'db_table': 'udise_code_mappings',
                'ordering': ['category', 'internal_value'],
                'unique_together': {('category', 'internal_value')},
            },
        ),
    ]
