# Generated by Django 6.0 on 2026-01-23 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_remove_student_student_admission_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique identifier code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Clear explanation of purpose')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether consent is mandatory for service delivery')),
                ('category', models.CharField(choices=[('EDUCATIONAL', 'Educational Activities'), ('ADMINISTRATIVE', 'Administrative'), ('COMMUNICATION', 'Communication'), ('HEALTH', 'Health & Safety'), ('FINANCIAL', 'Financial'), ('ANALYTICS', 'Analytics & Improvement'), ('THIRD_PARTY', 'Third-Party Sharing')], max_length=50)),
                ('legal_basis', models.TextField(help_text='Explanation of legal basis for processing')),
                ('retention_period_days', models.IntegerField(help_text='Number of days to retain data for this purpose')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consent Purpose',
                'verbose_name_plural': 'Consent Purposes',
                'db_table': 'privacy_consent_purpose',
                'ordering': ['is_mandatory', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('field_name', models.CharField(help_text="Field to be corrected (e.g., 'date_of_birth', 'aadhar_number')", max_length=100)),
                ('current_value', models.TextField()),
                ('corrected_value', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Correction Completed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_completed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests_filed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Correction Request',
                'verbose_name_plural': 'Correction Requests',
                'db_table': 'privacy_correction_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Deletion Completed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes on deletion')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_completed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_requests_filed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Deletion Request',
                'verbose_name_plural': 'Deletion Requests',
                'db_table': 'privacy_deletion_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grievance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('CONSENT_VIOLATION', 'Consent Violation'), ('DATA_BREACH', 'Data Breach'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('DATA_INACCURACY', 'Data Inaccuracy'), ('RETENTION_VIOLATION', 'Retention Policy Violation'), ('RIGHT_TO_ACCESS', 'Right to Access Denied'), ('RIGHT_TO_ERASURE', 'Right to Erasure Denied'), ('OTHER', 'Other Privacy Concern')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Must acknowledge within 24 hours', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Target: 72 hours for critical issues', null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grievances_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_grievances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='students.student')),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'db_table': 'privacy_grievance',
                'ordering': ['-filed_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal staff notes not visible to parent')),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='privacy.grievance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grievance Comment',
                'verbose_name_plural': 'Grievance Comments',
                'db_table': 'privacy_grievance_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_text', models.TextField(help_text='Exact text shown to parent when requesting consent')),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('EMAIL_OTP', 'Email OTP'), ('SMS_OTP', 'SMS OTP'), ('AADHAAR_VIRTUAL_TOKEN', 'Aadhaar Virtual Token'), ('EXISTING_IDENTITY', 'Existing Identity on File'), ('MANUAL_VERIFICATION', 'Manual Verification by School')], max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_data', models.JSONField(default=dict, help_text='Stores verification details (OTP timestamp, token reference, etc.)')),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_given', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='privacy.consentpurpose')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='students.student')),
            ],
            options={
                'verbose_name': 'Parental Consent',
                'verbose_name_plural': 'Parental Consents',
                'db_table': 'privacy_parental_consent',
            },
        ),
        migrations.CreateModel(
            name='ConsentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('REQUESTED', 'Consent Requested'), ('GIVEN', 'Consent Given'), ('VERIFIED', 'Verification Completed'), ('WITHDRAWN', 'Consent Withdrawn'), ('EXPIRED', 'Consent Expired'), ('RENEWED', 'Consent Renewed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField()),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='privacy.parentalconsent')),
            ],
            options={
                'verbose_name': 'Consent Audit Log',
                'verbose_name_plural': 'Consent Audit Logs',
                'db_table': 'privacy_consent_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataBreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breach_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('breach_type', models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('DATA_LOSS', 'Data Loss'), ('RANSOMWARE', 'Ransomware Attack'), ('ACCIDENTAL_DISCLOSURE', 'Accidental Disclosure'), ('THEFT', 'Physical Theft'), ('SYSTEM_VULNERABILITY', 'System Vulnerability Exploited'), ('OTHER', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk - Notification Required'), ('CRITICAL', 'Critical - Immediate Notification')], max_length=20)),
                ('data_affected', models.JSONField(default=list, help_text="List of data types compromised (e.g., ['Aadhar', 'Health Records'])")),
                ('students_affected_count', models.IntegerField(default=0)),
                ('discovered_at', models.DateTimeField(help_text='When breach was discovered')),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('reported_to_dpb_at', models.DateTimeField(blank=True, help_text='When reported to Data Protection Board', null=True)),
                ('parents_notified_at', models.DateTimeField(blank=True, null=True)),
                ('dpb_notification_sent', models.BooleanField(default=False)),
                ('parent_notifications_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('INVESTIGATING', 'Under Investigation'), ('CONTAINED', 'Contained'), ('NOTIFIED', 'Notifications Sent'), ('RESOLVED', 'Resolved')], default='DISCOVERED', max_length=20)),
                ('remediation_steps', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('students_affected', models.ManyToManyField(blank=True, related_name='data_breaches', to='students.student')),
            ],
            options={
                'verbose_name': 'Data Breach',
                'verbose_name_plural': 'Data Breaches',
                'db_table': 'privacy_data_breach',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['severity', '-discovered_at'], name='privacy_dat_severit_d0444c_idx'), models.Index(fields=['status', '-discovered_at'], name='privacy_dat_status_740a82_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status', '-filed_at'], name='privacy_gri_status_7c72f5_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['severity', '-filed_at'], name='privacy_gri_severit_250201_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['filed_by', '-filed_at'], name='privacy_gri_filed_b_7a6445_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalconsent',
            index=models.Index(fields=['student', 'purpose', 'consent_given'], name='privacy_par_student_ee002c_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalconsent',
            index=models.Index(fields=['parent_user', 'consent_date'], name='privacy_par_parent__acb79b_idx'),
        ),
        migrations.AddIndex(
            model_name='parentalconsent',
            index=models.Index(fields=['withdrawn', 'withdrawn_at'], name='privacy_par_withdra_c04d09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentalconsent',
            unique_together={('student', 'parent_user', 'purpose')},
        ),
        migrations.AddIndex(
            model_name='consentauditlog',
            index=models.Index(fields=['consent', '-timestamp'], name='privacy_con_consent_7053d2_idx'),
        ),
        migrations.AddIndex(
            model_name='consentauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='privacy_con_action_79a465_idx'),
        ),
    ]
