# Generated by Django 6.0 on 2026-01-24 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        ('students', '0005_convert_to_encrypted_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveDataAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('field_name', models.CharField(help_text='Name of sensitive field accessed', max_length=100)),
                ('field_value_hash', models.CharField(blank=True, help_text='SHA256 hash of accessed value (for integrity verification)', max_length=64)),
                ('access_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('EXPORT', 'Export'), ('DELETE', 'Delete')], default='VIEW', max_length=20)),
                ('access_reason', models.CharField(blank=True, help_text="Why the data was accessed (e.g., 'Admission form review')", max_length=200)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('has_valid_consent', models.BooleanField(default=False, help_text='Whether parent consent was verified at time of access')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for suspicious access pattern')),
                ('flag_reason', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('consent_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='privacy.consentpurpose')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accesses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_accesses', to='students.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_data_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensitive Data Access Log',
                'verbose_name_plural': 'Sensitive Data Access Logs',
                'db_table': 'privacy_sensitive_data_access',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessPatternAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('BULK_ACCESS', 'Bulk Data Access'), ('UNUSUAL_HOURS', 'Access During Unusual Hours'), ('UNAUTHORIZED_FIELD', 'Unauthorized Field Access'), ('REPEATED_FAILED_ACCESS', 'Repeated Failed Access Attempts'), ('NO_CONSENT', 'Access Without Valid Consent'), ('EXPORT_ANOMALY', 'Unusual Export Pattern')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('affected_students_count', models.IntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detection_rule', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Under Investigation'), ('FALSE_POSITIVE', 'False Positive'), ('CONFIRMED', 'Confirmed Violation'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('affected_students', models.ManyToManyField(blank=True, related_name='access_pattern_alerts', to='students.student')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_accesses', models.ManyToManyField(blank=True, related_name='alerts', to='privacy.sensitivedataaccess')),
            ],
            options={
                'verbose_name': 'Access Pattern Alert',
                'verbose_name_plural': 'Access Pattern Alerts',
                'db_table': 'privacy_access_pattern_alert',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sensitivedataaccess',
            index=models.Index(fields=['student', 'accessed_at'], name='privacy_sen_student_579149_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivedataaccess',
            index=models.Index(fields=['user', 'accessed_at'], name='privacy_sen_user_id_4466d0_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivedataaccess',
            index=models.Index(fields=['field_name', 'accessed_at'], name='privacy_sen_field_n_cd8c07_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivedataaccess',
            index=models.Index(fields=['is_flagged', 'reviewed_at'], name='privacy_sen_is_flag_ed3a32_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspatternalert',
            index=models.Index(fields=['user', 'detected_at'], name='privacy_acc_user_id_733f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspatternalert',
            index=models.Index(fields=['alert_type', 'severity'], name='privacy_acc_alert_t_d68181_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspatternalert',
            index=models.Index(fields=['status', 'detected_at'], name='privacy_acc_status_3e1bef_idx'),
        ),
    ]
