# Generated by Django 4.2.7 on 2026-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_academicyear_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_group', 'stream', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='class_group',
            field=models.CharField(choices=[('PRIMARY', 'Primary (Class 1-5)'), ('MIDDLE', 'Middle (Class 6-8)'), ('SECONDARY', 'Secondary (Class 9-10)'), ('SENIOR_SECONDARY', 'Senior Secondary (Class 11-12)')], default='PRIMARY', help_text='Class level group', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SCI', 'Science'), ('COM', 'Commerce'), ('HUM', 'Humanities'), ('VOC', 'Vocational'), ('IB_GROUP', 'IB Group')], default='GENERAL', help_text='Academic stream', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['class_group'], name='subjects_class_g_cbbc92_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['stream'], name='subjects_stream_0a6f66_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['class_group', 'stream'], name='subjects_class_g_883212_idx'),
        ),
    ]
