# Generated by Django 5.2.10 on 2026-02-08 11:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_class_group_stream_to_subject'),
        ('staff', '0004_remove_staffdocument_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Week start date')),
                ('end_date', models.DateField(help_text='Week end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Approver comments or general notes')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='staff.staffmember')),
            ],
            options={
                'db_table': 'lesson_plans',
                'ordering': ['-start_date', 'teacher'],
                'unique_together': {('teacher', 'section', 'subject', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unit_number', models.IntegerField(help_text='Chapter/Unit Number')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed content/topics description')),
                ('learning_objectives', models.TextField(blank=True)),
                ('expected_hours', models.DecimalField(decimal_places=2, default=0, help_text='Expected number of hours to complete this unit', max_digits=5)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weightage in exams', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='academics.class', verbose_name='Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='academics.subject')),
            ],
            options={
                'db_table': 'syllabus_units',
                'ordering': ['class_instance__class_order', 'subject__name', 'unit_number'],
                'unique_together': {('subject', 'class_instance', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='LessonPlanItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(help_text='Specific topic to be covered', max_length=255)),
                ('planned_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('resources_used', models.TextField(blank=True, help_text='Teaching aids, references, etc.')),
                ('homework', models.TextField(blank=True, help_text='Homework assigned')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.lessonplan')),
                ('syllabus_unit', models.ForeignKey(blank=True, help_text='Link to specific syllabus unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_items', to='academics.syllabusunit')),
            ],
            options={
                'db_table': 'lesson_plan_items',
                'ordering': ['planned_date'],
            },
        ),
    ]
