# Generated by Django 5.2.10 on 2026-02-18 09:00

from django.db import migrations, models


def backfill_class_groups(apps, schema_editor):
    """
    Backfill the class_group field for all existing Class records.
    Uses name-based detection: parse class number from name field.
    Name examples: 'LKG', 'UKG', 'Class 1', 'Class 12', '1', '12'
    """
    import re
    Class = apps.get_model('academics', 'Class')
    for cls in Class.objects.all():
        name_upper = cls.name.upper().strip()
        # Pre-primary detection by name keywords
        if any(kw in name_upper for kw in ('LKG', 'UKG', 'NURSERY', 'KG', 'PRE-PRIMARY',
                                            'PREPRIMARY', 'NURSERY', 'PLAYGROUP')):
            group = 'PRE_PRIMARY'
        else:
            # Extract numeric class number from name like "Class 1", "1", "Grade 12", "12"
            m = re.search(r'\b(\d{1,2})\b', cls.name)
            if m:
                num = int(m.group(1))
                if num <= 5:
                    group = 'PRIMARY'
                elif num <= 8:
                    group = 'MIDDLE'
                elif num <= 10:
                    group = 'SECONDARY'
                else:
                    group = 'SENIOR_SECONDARY'
            else:
                # Fallback to class_order if no number in name
                if cls.class_order <= 2:
                    group = 'PRE_PRIMARY'
                elif cls.class_order <= 7:
                    group = 'PRIMARY'
                elif cls.class_order <= 10:
                    group = 'MIDDLE'
                elif cls.class_order <= 12:
                    group = 'SECONDARY'
                else:
                    group = 'SENIOR_SECONDARY'
        cls.class_group = group
        cls.save(update_fields=['class_group'])


def backfill_subject_groups(apps, schema_editor):
    """
    Update class_group for known subject names that span multiple groups.
    Sets reasonable defaults — admins can refine via Django admin.
    """
    Subject = apps.get_model('academics', 'Subject')

    # Senior Secondary only
    ss_subjects = ['Physics', 'Chemistry', 'Biology', 'Accountancy', 'Business Studies',
                   'Economics', 'Political Science', 'History', 'Geography']
    Subject.objects.filter(name__in=ss_subjects).update(class_group='SENIOR_SECONDARY')

    # Secondary (9-10) and above — keep SECONDARY as group (these start from Class 9)
    secondary_subjects = ['Science']  # consolidated Science for 9-10
    Subject.objects.filter(name__in=secondary_subjects).update(class_group='SECONDARY')

    # Middle school subjects (6-8)
    middle_subjects = ['Social Science']
    Subject.objects.filter(name__in=middle_subjects).update(class_group='MIDDLE')

    # Pre-primary
    preprimary_subjects = ['Drawing', 'EVS']
    Subject.objects.filter(name__in=preprimary_subjects).update(class_group='PRIMARY')

    # Cross-level subjects that appear in all groups — leave as PRIMARY (most common default)
    # Admins can refine: Mathematics, English, Hindi, Computer Science, Physical Education


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_lessonplan_syllabusunit_lessonplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_group',
            field=models.CharField(blank=True, choices=[('PRE_PRIMARY', 'Pre-Primary (LKG/UKG/Nursery)'), ('PRIMARY', 'Primary (Class 1-5)'), ('MIDDLE', 'Middle (Class 6-8)'), ('SECONDARY', 'Secondary (Class 9-10)'), ('SENIOR_SECONDARY', 'Senior Secondary (Class 11-12)')], db_index=True, help_text='Auto-set: PRE_PRIMARY for LKG/UKG, PRIMARY for 1-5, MIDDLE for 6-8, SECONDARY for 9-10, SENIOR_SECONDARY for 11-12', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_order',
            field=models.IntegerField(help_text='Order of class: -2=LKG, -1=UKG, 1-12 for numbered classes', unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='display_name',
            field=models.CharField(help_text='Display name: Class 1, Grade 1, LKG, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Class name: LKG, UKG, 1, 2, ..., 12', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_group',
            field=models.CharField(choices=[('PRE_PRIMARY', 'Pre-Primary (LKG/UKG/Nursery)'), ('PRIMARY', 'Primary (Class 1-5)'), ('MIDDLE', 'Middle (Class 6-8)'), ('SECONDARY', 'Secondary (Class 9-10)'), ('SENIOR_SECONDARY', 'Senior Secondary (Class 11-12)')], default='PRIMARY', help_text='Class level group', max_length=20),
        ),
        # Backfill class_group for all existing Class records
        migrations.RunPython(backfill_class_groups, migrations.RunPython.noop),
        # Update subject class_group for known subjects
        migrations.RunPython(backfill_subject_groups, migrations.RunPython.noop),
    ]
