# Generated by Django 5.2.10 on 2026-02-08 11:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0007_tenantconfig_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('partner_code', models.CharField(help_text='Unique code for tracking referrals (e.g., PARTNER001)', max_length=20, unique=True)),
                ('commission_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Subscription'), ('FLAT', 'Flat Amount per Conversion'), ('TIERED', 'Tiered Based on Volume')], default='PERCENTAGE', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('flat_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('total_leads', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public_partners',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner_code'], name='public_part_partner_71e054_idx'), models.Index(fields=['email'], name='public_part_email_a3cb9b_idx'), models.Index(fields=['status'], name='public_part_status_3ebc9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('estimated_students', models.IntegerField(blank=True, help_text='Estimated number of students', null=True)),
                ('board', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted'), ('DEMO_SCHEDULED', 'Demo Scheduled'), ('DEMO_COMPLETED', 'Demo Completed'), ('NEGOTIATION', 'In Negotiation'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('INVALID', 'Invalid Lead')], default='NEW', max_length=20)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, choices=[('PRICE', 'Price Too High'), ('FEATURES', 'Missing Features'), ('COMPETITOR', 'Chose Competitor'), ('NOT_READY', 'Not Ready to Buy'), ('NO_RESPONSE', 'No Response'), ('OTHER', 'Other')], max_length=20)),
                ('lost_notes', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('last_contacted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Sales person assigned to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='tenants.school')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='partners.partner')),
            ],
            options={
                'db_table': 'public_leads',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subscription_tier', models.CharField(blank=True, help_text='Apply only to specific subscription tier (BASIC, STANDARD, PREMIUM, ENTERPRISE)', max_length=20)),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Subscription'), ('FLAT', 'Flat Amount'), ('PERCENTAGE_RECURRING', 'Percentage for Recurring Months')], default='PERCENTAGE', max_length=30)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('recurring_months', models.IntegerField(default=0, help_text='Number of months to pay recurring commission (0 = one-time only)', validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, help_text='Leave blank for global rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_rules', to='partners.partner')),
            ],
            options={
                'db_table': 'public_commission_rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_number', models.CharField(help_text='Unique payout reference number (e.g., PAY-2026-01-001)', max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_count', models.IntegerField(default=0, help_text='Number of commissions included in this payout')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=0, help_text='TDS percentage deducted', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount after TDS deduction', max_digits=12)),
                ('invoice_url', models.URLField(blank=True)),
                ('payment_receipt_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payouts', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='partners.partner')),
            ],
            options={
                'db_table': 'public_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_amount', models.DecimalField(decimal_places=2, help_text='Original subscription amount', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_type', models.CharField(choices=[('INITIAL', 'Initial Conversion'), ('RECURRING', 'Recurring Monthly'), ('RENEWAL', 'Subscription Renewal'), ('UPGRADE', 'Plan Upgrade')], default='INITIAL', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('earned_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to='tenants.school')),
                ('commission_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_commissions', to='partners.commissionrule')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.lead')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.partner')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='partners.payout')),
            ],
            options={
                'db_table': 'public_commissions',
                'ordering': ['-earned_date'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['partner', 'status'], name='public_lead_partner_301040_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='public_lead_status_b8efe5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='public_lead_email_f1eaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['converted_school'], name='public_lead_convert_80a57a_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['partner', 'status'], name='public_payo_partner_e50f21_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['payout_number'], name='public_payo_payout__80c37e_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='public_payo_status_b75911_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['partner', 'status'], name='public_comm_partner_8f722b_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status'], name='public_comm_status_58bfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['earned_date'], name='public_comm_earned__21e978_idx'),
        ),
    ]
