# Generated by Django 4.2.7 on 2026-02-09 06:09

import apps.core.encryption.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('LMS', 'Learning Management System'), ('ERP', 'Enterprise Resource Planning'), ('PAYMENT', 'Payment Gateway'), ('GOVT', 'Government System'), ('MARKETPLACE', 'Marketplace App'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('developer_email', models.EmailField(blank=True, max_length=254)),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='Schema for configuration fields')),
                ('is_active', models.BooleanField(default=True)),
                ('icon_url', models.URLField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='e.g. student.created', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('payload_schema', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'webhook_events',
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target_url', models.URLField()),
                ('secret_key', apps.core.encryption.fields.EncryptedCharField(help_text='HMAC secret key for signing payloads', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers to send')),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='integrations.webhookevent')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='integrations.integration')),
            ],
            options={
                'db_table': 'webhook_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhooksubscription')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, help_text='Public Client ID or API Key ID', max_length=255)),
                ('client_secret', apps.core.encryption.fields.EncryptedCharField(blank=True, help_text='Encrypted Client Secret', max_length=512, null=True)),
                ('api_key', apps.core.encryption.fields.EncryptedCharField(blank=True, help_text='Encrypted API Key (if different from secret)', max_length=512, null=True)),
                ('access_token', apps.core.encryption.fields.EncryptedCharField(blank=True, max_length=1024, null=True)),
                ('refresh_token', apps.core.encryption.fields.EncryptedCharField(blank=True, max_length=1024, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Tenant-specific configuration values')),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses for inbound requests')),
                ('rate_limit_requests', models.PositiveIntegerField(default=1000, help_text='Max requests per hour for this integration')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integrations.integration')),
            ],
            options={
                'db_table': 'integration_credentials',
            },
        ),
    ]
