# Generated by Django 5.2.10 on 2026-02-09 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_lessonplan_syllabusunit_lessonplanitem'),
        ('staff', '0005_staffroleassignment'),
        ('students', '0007_alter_student_current_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('SPORTS', 'Sports'), ('ARTS', 'Arts & Culture'), ('STEM', 'STEM/Technology'), ('COMMUNITY', 'Community Service')], default='ACADEMIC', max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='clubs/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('in_charge', models.ForeignKey(help_text='Teacher in-charge of the club', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clubs', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='ClubActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.club')),
            ],
            options={
                'verbose_name': 'Club Activity',
                'verbose_name_plural': 'Club Activities',
                'db_table': 'club_activities',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='activities.clubactivity')),
            ],
            options={
                'db_table': 'club_activity_attendance',
                'unique_together': {('activity', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('HEAD', 'Student Head')], default='MEMBER', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='academics.academicyear')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='activities.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='students.student')),
            ],
            options={
                'db_table': 'club_memberships',
                'unique_together': {('student', 'club', 'academic_year')},
            },
        ),
    ]
