# Generated by Django 4.2.7 on 2025-12-21 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Code must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')])),
                ('schema_name', models.CharField(help_text='PostgreSQL schema name for this tenant', max_length=63, unique=True)),
                ('subdomain', models.CharField(help_text='Subdomain for accessing the school (e.g., schoolname.schoolmgmt.com)', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must contain only lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('primary_board', models.CharField(choices=[('CBSE', 'CBSE - Central Board of Secondary Education'), ('ICSE', 'ICSE - Indian Certificate of Secondary Education'), ('MPBSE', 'MPBSE - Madhya Pradesh Board of Secondary Education'), ('STATE', 'State Board'), ('IB', 'International Baccalaureate'), ('CAMBRIDGE', 'Cambridge International')], default='CBSE', max_length=20)),
                ('supported_boards', models.JSONField(default=list, help_text='List of all boards supported by this school')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#1976d2', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#dc004e', help_text='Hex color code', max_length=7)),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
                ('db_host', models.CharField(blank=True, help_text='Leave blank to use default', max_length=255)),
                ('db_port', models.IntegerField(blank=True, null=True)),
                ('db_name', models.CharField(blank=True, help_text='Leave blank to use default', max_length=63)),
                ('db_user', models.CharField(blank=True, max_length=63)),
                ('db_password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('auto_create_schema', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict, help_text='School-specific settings and configurations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_students', models.IntegerField(default=500)),
                ('max_teachers', models.IntegerField(default=50)),
                ('max_staff', models.IntegerField(default=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public_subscriptions',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_online_payments', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=True)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_biometric_attendance', models.BooleanField(default=False)),
                ('enable_mobile_app', models.BooleanField(default=True)),
                ('enable_parent_portal', models.BooleanField(default=True)),
                ('enable_library', models.BooleanField(default=True)),
                ('enable_transport', models.BooleanField(default=True)),
                ('enable_hostel', models.BooleanField(default=False)),
                ('enable_hr_payroll', models.BooleanField(default=True)),
                ('academic_year_start_month', models.IntegerField(default=4, help_text='Month number (1-12)')),
                ('working_days', models.JSONField(default=list, help_text='Working days (0=Monday, 6=Sunday)')),
                ('attendance_marking_time', models.TimeField(default='10:00:00')),
                ('late_arrival_time', models.TimeField(default='09:30:00')),
                ('late_fee_enabled', models.BooleanField(default=True)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('late_fee_grace_days', models.IntegerField(default=5)),
                ('sms_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('email_quota_monthly', models.IntegerField(default=10000)),
                ('custom_settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenants.school')),
            ],
            options={
                'db_table': 'public_tenant_configs',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='tenants.subscription'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this school')),
                ('is_https', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.school')),
            ],
            options={
                'db_table': 'public_domains',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['schema_name'], name='public_scho_schema__f6f1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['subdomain'], name='public_scho_subdoma_b32d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='public_scho_is_acti_06da3f_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain', 'is_active'], name='public_doma_domain_e043b0_idx'),
        ),
    ]
