# Generated by Django 6.0 on 2026-01-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='School-specific settings and configurations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='supported_boards',
            field=models.JSONField(blank=True, default=list, help_text='List of all boards supported by this school'),
        ),
    ]
