# Generated by Django 4.2.7 on 2026-02-01 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_school_settings_alter_school_supported_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique feature code, e.g. "ai_timetable_generator"', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable feature name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('ACADEMICS', 'Academics'), ('COMMUNICATION', 'Communication'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('AI_PREMIUM', 'AI & Premium')], default='CORE', max_length=20)),
                ('minimum_tier', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='BASIC', help_text='Minimum subscription tier required for this feature', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Global kill switch — disables feature for ALL tenants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public_feature_definitions',
                'ordering': ['category', 'minimum_tier', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.CharField(blank=True, help_text='Reason for manual override (e.g., "Trial period for premium feature")', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_assignments', to='tenants.featuredefinition')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.school')),
            ],
            options={
                'db_table': 'public_tenant_features',
                'ordering': ['school', 'feature__category', 'feature__name'],
                'unique_together': {('school', 'feature')},
            },
        ),
    ]
