# Generated by Django 6.0 on 2026-02-02 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_featuredefinition_subscription_tier_tenantfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='db_password',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use vault or encrypted storage for credentials', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='schema_name',
            field=models.CharField(help_text='PostgreSQL schema name for this tenant', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Schema name must start with a lowercase letter and contain only lowercase letters, numbers, and underscores', regex='^[a-z][a-z0-9_]*$')]),
        ),
    ]
