# Generated by Django 5.2.10 on 2026-02-07 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rename_school_domain_tenant_alter_domain_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dns_record',
            field=models.CharField(blank=True, help_text='TXT record for domain verification', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_method', models.CharField(default='RAZORPAY', max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='SUCCESS', max_length=20)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='tenants.school')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscription')),
            ],
            options={
                'db_table': 'public_subscription_billing',
                'ordering': ['-billing_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_light', models.ImageField(blank=True, help_text='Logo for light backgrounds', null=True, upload_to='branding/logos/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo for dark backgrounds', null=True, upload_to='branding/logos/')),
                ('icon', models.ImageField(blank=True, help_text='Favicon / App Icon', null=True, upload_to='branding/icons/')),
                ('primary_color', models.CharField(default='#1976d2', help_text='Primary brand color', max_length=7)),
                ('secondary_color', models.CharField(default='#dc004e', help_text='Secondary brand color', max_length=7)),
                ('accent_color', models.CharField(default='#f50057', help_text='Accent color for highlights', max_length=7)),
                ('font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins')], default='Inter', max_length=50)),
                ('request_login', models.BooleanField(default=True, help_text='Show "Request Info" on login page')),
                ('login_layout', models.CharField(choices=[('SIMPLE', 'Simple'), ('SPLIT', 'Split Screen'), ('CENTERED', 'Centered Card')], default='SIMPLE', max_length=20)),
                ('css_overrides', models.TextField(blank=True, help_text='Custom CSS for web portal')),
                ('email_header_image', models.ImageField(blank=True, null=True, upload_to='branding/email/')),
                ('pdf_header_image', models.ImageField(blank=True, null=True, upload_to='branding/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.school')),
            ],
            options={
                'db_table': 'public_tenant_branding',
            },
        ),
    ]
