# Generated by Django 4.2.7 on 2026-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_domain_dns_record_domain_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', help_text='Default language for tenant users and notifications', max_length=10),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='category',
            field=models.CharField(choices=[('CORE', 'Core'), ('ACADEMICS', 'Academics'), ('COMMUNICATION', 'Communication'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('AI_PREMIUM', 'AI & Premium'), ('INTEGRATION', 'Integrations & Marketplace')], default='CORE', max_length=20),
        ),
    ]
