# Generated by Django 5.2.10 on 2026-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenantconfig_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('gu', 'Gujarati')], default='en', help_text='Default language for tenant users and notifications', max_length=10),
        ),
    ]
