# Generated by Django 6.0 on 2026-01-24 04:32

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_student_admission_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='samagra_family_id',
            field=models.CharField(blank=True, db_index=True, help_text='8-digit Samagra Family ID (SSMID) - Madhya Pradesh only. Required for scholarships and welfare schemes.', max_length=8, null=True, validators=[apps.core.validators.validate_samagra_family_id]),
        ),
        migrations.AddField(
            model_name='student',
            name='samagra_id_verification_date',
            field=models.DateTimeField(blank=True, help_text='Date when Samagra ID was last verified', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='samagra_id_verified',
            field=models.BooleanField(default=False, help_text='Whether Samagra ID has been verified against SSSM portal'),
        ),
        migrations.AddField(
            model_name='student',
            name='samagra_member_id',
            field=models.CharField(blank=True, db_index=True, help_text='9-digit Samagra Member ID (SSRNID) - Individual student identifier. Must be unique across all students.', max_length=9, null=True, unique=True, validators=[apps.core.validators.validate_samagra_member_id]),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number (unique identifier)', max_length=12, null=True, unique=True, validators=[apps.core.validators.validate_aadhar_number]),
        ),
    ]
