# Generated by Django 6.0 on 2026-01-24 07:44

import apps.core.encryption.fields
import apps.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_samagra_id_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_number',
            field=apps.core.encryption.fields.EncryptedCharField(blank=True, help_text='12-digit Aadhaar number (unique identifier) - Encrypted at rest', max_length=12, null=True, validators=[apps.core.validators.validate_aadhar_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_annual_income',
            field=apps.core.encryption.fields.EncryptedDecimalField(blank=True, decimal_places=2, help_text='Father annual income - Encrypted for privacy', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_annual_income',
            field=apps.core.encryption.fields.EncryptedDecimalField(blank=True, decimal_places=2, help_text='Mother annual income - Encrypted for privacy', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='samagra_family_id',
            field=apps.core.encryption.fields.EncryptedCharField(blank=True, help_text='8-digit Samagra Family ID (SSMID) - Madhya Pradesh only. Encrypted at rest.', max_length=8, null=True, validators=[apps.core.validators.validate_samagra_family_id]),
        ),
        migrations.AlterField(
            model_name='student',
            name='samagra_member_id',
            field=apps.core.encryption.fields.EncryptedCharField(blank=True, help_text='9-digit Samagra Member ID (SSRNID) - Individual student identifier. Encrypted at rest.', max_length=9, null=True, validators=[apps.core.validators.validate_samagra_member_id]),
        ),
    ]
