# Generated by Django 5.2.10 on 2026-02-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_convert_to_encrypted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_ADMIN', 'Submitted to Admin'), ('SENT_TO_PARENT', 'Sent to Parent'), ('PARENT_REVIEWED', 'Parent Reviewed'), ('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('PASSED_OUT', 'Passed Out')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
