# Generated by Django 4.2.7 on 2026-02-01 05:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('STUDENTS', 'Students'), ('ACADEMICS', 'Academics'), ('ATTENDANCE', 'Attendance'), ('FEE', 'Fee & Finance'), ('EXAM', 'Examinations'), ('LIBRARY', 'Library'), ('TRANSPORT', 'Transport'), ('HOSTEL', 'Hostel'), ('HR_PAYROLL', 'HR & Payroll'), ('ADMISSIONS', 'Admissions'), ('CUSTOM', 'Custom')], help_text='Module this report belongs to', max_length=30)),
                ('query_config', models.JSONField(default=dict, help_text='JSON configuration defining data source, filters, columns, and aggregations')),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for report layout (headers, footers, grouping, etc.)')),
                ('default_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted by users')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_templates',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(default=dict, help_text='Saved filter/parameter configuration')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('is_pinned', models.BooleanField(default=False, help_text='Whether this report is pinned to dashboard')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_by_users', to='reports.reporttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'db_table': 'report_saved',
                'ordering': ['-is_pinned', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly schedules (0=Monday)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly/quarterly/yearly schedules', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('time_of_day', models.TimeField(help_text='Time of day to generate the report')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('parameters', models.JSONField(default=dict, help_text='Fixed parameters to apply each time the report is generated')),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses to send generated reports to')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='When this schedule was last executed', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='When this schedule will next execute', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Name/title of the generated report', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('STUDENTS', 'Students'), ('ACADEMICS', 'Academics'), ('ATTENDANCE', 'Attendance'), ('FEE', 'Fee & Finance'), ('EXAM', 'Examinations'), ('LIBRARY', 'Library'), ('TRANSPORT', 'Transport'), ('HOSTEL', 'Hostel'), ('HR_PAYROLL', 'HR & Payroll'), ('ADMISSIONS', 'Admissions'), ('CUSTOM', 'Custom')], help_text='Module this report belongs to', max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters/filters applied when generating this report')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Generated report file', null=True, upload_to='reports/generated/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('row_count', models.PositiveIntegerField(default=0, help_text='Number of data rows in the report')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if report generation failed')),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the report generation completed', null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used to generate this report (null if ad-hoc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'db_table': 'report_generated',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['module'], name='report_temp_module_cfb3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_system'], name='report_temp_is_syst_6465c9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active'], name='report_sche_is_acti_12ab8c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_run'], name='report_sche_next_ru_270fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['module'], name='report_gene_module_ebfda0_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status'], name='report_gene_status_503a76_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by'], name='report_gene_generat_b2f636_idx'),
        ),
    ]
