# Generated by Django 5.2.10 on 2026-02-11 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to generate this report (null if ad-hoc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_reports', to='reports.reporttemplate'),
        ),
    ]
