# Generated by Django 4.2.7 on 2026-02-01 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_remove_academicyear_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application_number', models.CharField(db_index=True, help_text='Auto-generated unique application number', max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('board', models.CharField(blank=True, help_text='Previous school board (CBSE, ICSE, State, etc.)', max_length=50)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage obtained in previous class', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='academics.academicyear')),
                ('class_applied', models.ForeignKey(help_text='Class for which admission is applied', on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='academics.class')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'db_table': 'admission_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Name of the student or parent enquiring', max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('enquiry_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk In'), ('PHONE', 'Phone'), ('ONLINE', 'Online'), ('REFERRAL', 'Referral')], default='WALK_IN', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to follow up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('class_applied', models.ForeignKey(blank=True, help_text='Class for which admission is enquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_enquiries', to='academics.class')),
            ],
            options={
                'verbose_name': 'Admission Enquiry',
                'verbose_name_plural': 'Admission Enquiries',
                'db_table': 'admission_enquiries',
                'ordering': ['-enquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('REPORT_CARD', 'Report Card'), ('AADHAR_CARD', 'Aadhar Card'), ('PHOTOS', 'Photographs'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='admissions/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_admission_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Document',
                'verbose_name_plural': 'Admission Documents',
                'db_table': 'admission_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='enquiry',
            field=models.ForeignKey(blank=True, help_text='Linked enquiry if converted from enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='admissions.admissionenquiry'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdmissionSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_seats', models.PositiveIntegerField(default=40, help_text='Total seats available for admission')),
                ('filled_seats', models.PositiveIntegerField(default=0, help_text='Number of seats already filled')),
                ('application_start_date', models.DateField(help_text='Date from which applications are accepted')),
                ('application_end_date', models.DateField(help_text='Last date for application submission')),
                ('entrance_test_required', models.BooleanField(default=False, help_text='Whether entrance test is required for admission')),
                ('interview_required', models.BooleanField(default=False, help_text='Whether interview is required for admission')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Application processing fee', max_digits=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_settings', to='academics.academicyear')),
                ('class_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_settings', to='academics.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Admission Setting',
                'verbose_name_plural': 'Admission Settings',
                'db_table': 'admission_settings',
                'ordering': ['academic_year', 'class_applied'],
                'unique_together': {('academic_year', 'class_applied')},
            },
        ),
        migrations.AddIndex(
            model_name='admissionenquiry',
            index=models.Index(fields=['status'], name='admission_e_status_342718_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionenquiry',
            index=models.Index(fields=['enquiry_date'], name='admission_e_enquiry_3069a9_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionenquiry',
            index=models.Index(fields=['source'], name='admission_e_source_4348eb_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['status'], name='admission_a_status_ab03e4_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['application_number'], name='admission_a_applica_5ddfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['student_name'], name='admission_a_student_212d7b_idx'),
        ),
    ]
