# Generated by Django 5.2.10 on 2026-02-11 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionenquiry',
            name='enquiry_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
