# Generated by Django 5.2.10 on 2026-02-09 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_lessonplan_syllabusunit_lessonplanitem'),
        ('students', '0007_alter_student_current_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color_code', models.CharField(help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='houses/logos/')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'db_table': 'houses',
            },
        ),
        migrations.CreateModel(
            name='HousePointLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(help_text='Points awarded (can be negative for penalties)')),
                ('reason', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('SPORTS', 'Sports/Athletics'), ('CULTURAL', 'Cultural/Arts'), ('DISCIPLINE', 'Discipline/Conduct'), ('LEADERSHIP', 'Leadership'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('awarded_date', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awarded_house_points', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_log', to='houses.house')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_points', to='students.student')),
            ],
            options={
                'db_table': 'house_points_log',
                'ordering': ['-awarded_date'],
            },
        ),
        migrations.CreateModel(
            name='HouseMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('HOUSE_CAPTAIN', 'House Captain'), ('VICE_CAPTAIN', 'Vice Captain'), ('PREFECT', 'Prefect'), ('SPORTS_CAPTAIN', 'Sports Captain')], default='MEMBER', max_length=20)),
                ('points_contributed', models.IntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_memberships', to='academics.academicyear')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='houses.house')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_membership', to='students.student')),
            ],
            options={
                'db_table': 'house_memberships',
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
